version: "3"

services:
  redis:
    image: redis:5.0
    ports:
      - 6379:6379
  dojo:
    build:
      context: .
      dockerfile: docker/Dockerfile
    environment:
      MYSQL_USER: root
      MYSQL_PASSWORD: ca-tech-dojo
      MYSQL_HOST: mysql
      MYSQL_PORT: 3306
      MYSQL_DATABASE: dojo_api
    ports:
      - "8080:8080"
    volumes:
      - "./:/go/src/github.com/22dojo-online"
    depends_on:
      - mysql

  mysql:
    image: mysql:5.7
    expose:
      - "3306"
    restart: always
    volumes:
      - ./db/init:/docker-entrypoint-initdb.d
      - db-data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: "ca-tech-dojo"
      MYSQL_DATABASE: dojo_api

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    environment:
      PMA_ARBITRARY: 1
      PMA_HOST: mysql
      PMA_USER: root
      PMA_PASSWORD: "ca-tech-dojo"
    links:
      - mysql
    ports:
      - 4000:80

  swagger-ui:
    image: swaggerapi/swagger-ui:latest
    environment:
      SWAGGER_JSON: /api/api-document.yaml
    volumes:
      - ./api-document.yaml:/api/api-document.yaml:ro
    ports:
      - 127.0.0.1:3000:8080

  proxy:
    image: nginx:latest
    volumes:
    - ./docker/proxy.conf:/etc/nginx/conf.d/default.conf
    ports:
    - "3010:3010"

volumes:
  db-data:
    driver: local
