name: test

on:
  push:
    branches:
      - feature/daiki_kubo/githubAction
  pull_request:

jobs:
  test:
    name: go test
    strategy:
      matrix:
        go-version: [1.16.x, 1.17.x]
    runs-on: ubuntu-20.04

    steps:
      - name: checkout code into the Go module directory
        uses: actions/checkout@v2
      
      - name: set up Go 1.1x
        uses: actions/setup-go@v2
        with:
          go-version: ${{ matrix.go-version }}