name: test

on: [push, pull_request]

jobs:
  test:
    name: go test
    strategy:
      matrix:
        go-version: [1.17.x]
    runs-on: ubuntu-20.04

    steps:
      - name: checkout code into the Go module directory
        uses: actions/checkout@v2
      
      - name: set up Go 1.17.x
        uses: actions/setup-go@v2
        with:
          go-version: ${{ matrix.go-version }}

      - name: restore cache # modにキャッシュを効かせる
        uses: actions/cache@v2
        with:
          path: |
            ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-
      
      - name: get dependencies
        run: | 
          go mod download

      - run: go test ./pkg/router -v -coverprofile=coverage.txt -race -vet=off
        env:
          MYSQL_USERNAME: root
          MYSQL_PASSWORD: ca-tech-dojo
          MYSQL_HOSTNAME: 127.0.0.1
          MYSQL_DATABASE: dojo_api
      - uses: actions/upload-artifact@v2.3.1
        with:
          name: coverage.txt
          path: coverage.txt
            - run: go test ./pkg/router -v -coverprofile=coverage.txt -race -vet=off
        env:
          MYSQL_USERNAME: root
          MYSQL_PASSWORD: ca-tech-dojo
          MYSQL_HOSTNAME: 127.0.0.1
          MYSQL_DATABASE: dojo_api
      - uses: actions/upload-artifact@v2.3.1
        with:
          name: coverage.txt
          path: coverage.txt

      
        