name: test

on:
  push:
    branches:
      - feature/daiki_kubo/githubAction
  pull_request:

jobs:
  test:
    name: go test
    strategy:
      matrix:
        go-version: [1.16.x, 1.17.x]
    runs-on: ubuntu-20.04

    steps:
      - name: checkout code into the Go module directory
        uses: actions/checkout@v2
      
      - name: set up Go 1.1x
        uses: actions/setup-go@v2
        with:
          go-version: ${{ matrix.go-version }}

      # - name: use cache # ビルド時にキャッシュを聞かせる
      #   uses: actions/cache@v2
      #   with:
      #     path: |
      #       ~/go/pkg/mod
      #       ~/.cache/go-build
      #     key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
      #     restore-keys: |
      #       ${{ runner.os }}-go-
      
      # - name: get dependencies
      #   run: | 
      #     go mod download
    
    # ビルドテストの開始 (セットアップ必須)
    build:
      needs: setup
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v2
        - name: build
          run: go build ./...

      # unit やモックテストの開始 (セットアップ必須)
    test:
      needs: setup
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v2
        - name: test
          run: go test ./... -v
      
      # - name: Test
      #   run: 
      #     go test -race -coverprofile="coverage.txt" -covermode=atomic ./...

      # - name: upload coverage
      #   uses: codecov/codecov-action@v1
      #   with:
      #     token: ${{ secrets.CODECOV_TOKEN }}
        
      
        